tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# Official Amazon AWS command-line interface
brew "awscli"
# General-purpose scripting language
brew "php"
# Dependency Manager for PHP
brew "composer"
# General-purpose scripting language
brew "php@7.4"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# JavaScript toolchain manager for reproducible environments
brew "volta"
# Tracks most-used directories to make cd smarter
brew "z"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# View, print, and comment on PDF documents
cask "adobe-acrobat-reader"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Collaborative team software
cask "figma"
# Utility to hide menu bar items
cask "hiddenbar"
# Open-source keystroke visualizer
cask "keycastr"
# Privacy-first, open-source platform for knowledge sharing and management
cask "logseq"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organized
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# HTTP client that helps testing and describing APIs
cask "paw"
# Collaboration platform for API development
cask "postman"
# Control your tools with a few keystrokes
cask "raycast"
# Visible indicator of the current input source
cask "showyedge"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Video game digital distribution service
cask "steam"
# Break time reminder app
cask "stretchly"
# IDE, client, and GUI for MongoDB
cask "studio-3t"
# Native GUI tool for relational databases
cask "tableplus"
# Development environment
cask "vagrant"
# Multimedia player
cask "vlc"
# Rust-based terminal
cask "warp"
# Mind mapping and brainstorming tool
cask "xmind"
